### ISSUE TITLE
Try to use this compose file, i got this fail

### ISSUE THREAD

**Issue by Hans3nn** [Soren90/cs2-docker#13]
The logs

`mkdir: cannot create directory '/mnt/server/cs2': Permission denied
cp: target '/mnt/server/cs2/game/csgo/cfg' is not a directory
/entrypoint.sh: line 23: /mnt/server/cs2/game/csgo/cfg/autoexec.cfg: No such file or directory
/entrypoint.sh: line 55: /mnt/server/steamcmd/steamcmd.sh: No such file or directory
mkdir: cannot create directory '/mnt/server/.steam': Permission denied
mkdir: cannot create directory '/mnt/server/.steam': Permission denied
cp: cannot stat '/mnt/server/steamcmd/linux32/steamclient.so': No such file or directory
cp: cannot stat '/mnt/server/steamcmd/linux64/steamclient.so': No such file or directory
/entrypoint.sh: line 65: /mnt/server/cs2/game/cs2.sh: No such file or directory
mkdir: cannot create directory '/mnt/server/cs2': Permission denied
cp: target '/mnt/server/cs2/game/csgo/cfg' is not a directory
/entrypoint.sh: line 23: /mnt/server/cs2/game/csgo/cfg/autoexec.cfg: No such file or directory
/entrypoint.sh: line 55: /mnt/server/steamcmd/steamcmd.sh: No such file or directory
mkdir: cannot create directory '/mnt/server/.steam': Permission denied
mkdir: cannot create directory '/mnt/server/.steam': Permission denied
cp: cannot stat '/mnt/server/steamcmd/linux32/steamclient.so': No such file or directory
cp: cannot stat '/mnt/server/steamcmd/linux64/steamclient.so': No such file or directory
/entrypoint.sh: line 65: /mnt/server/cs2/game/cs2.sh: No such file or directory
mkdir: cannot create directory '/mnt/server/cs2': Permission denied
cp: target '/mnt/server/cs2/game/csgo/cfg' is not a directory
/entrypoint.sh: line 23: /mnt/server/cs2/game/csgo/cfg/autoexec.cfg: No such file or directory
/entrypoint.sh: line 55: /mnt/server/steamcmd/steamcmd.sh: No such file or directory
mkdir: cannot create directory '/mnt/server/.steam': Permission denied
mkdir: cannot create directory '/mnt/server/.steam': Permission denied
cp: cannot stat '/mnt/server/steamcmd/linux32/steamclient.so': No such file or directory
cp: cannot stat '/mnt/server/steamcmd/linux64/steamclient.so': No such file or directory
/entrypoint.sh: line 65: /mnt/server/cs2/game/cs2.sh: No such file or directory
mkdir: cannot create directory '/mnt/server/cs2': Permission denied
cp: target '/mnt/server/cs2/game/csgo/cfg' is not a directory
/entrypoint.sh: line 23: /mnt/server/cs2/game/csgo/cfg/autoexec.cfg: No such file or directory
/entrypoint.sh: line 55: /mnt/server/steamcmd/steamcmd.sh: No such file or directory
mkdir: cannot create directory '/mnt/server/.steam': Permission denied
mkdir: cannot create directory '/mnt/server/.steam': Permission denied
cp: cannot stat '/mnt/server/steamcmd/linux32/steamclient.so': No such file or directory
cp: cannot stat '/mnt/server/steamcmd/linux64/steamclient.so': No such file or directory
/entrypoint.sh: line 65: /mnt/server/cs2/game/cs2.sh: No such file or directory
mkdir: cannot create directory '/mnt/server/cs2': Permission denied
cp: target '/mnt/server/cs2/game/csgo/cfg' is not a directory
/entrypoint.sh: line 23: /mnt/server/cs2/game/csgo/cfg/autoexec.cfg: No such file or directory
/entrypoint.sh: line 55: /mnt/server/steamcmd/steamcmd.sh: No such file or directory
mkdir: cannot create directory '/mnt/server/.steam': Permission denied
mkdir: cannot create directory '/mnt/server/.steam': Permission denied
cp: cannot stat '/mnt/server/steamcmd/linux32/steamclient.so': No such file or directory
cp: cannot stat '/mnt/server/steamcmd/linux64/steamclient.so': No such file or directory
/entrypoint.sh: line 65: /mnt/server/cs2/game/cs2.sh: No such file or directory
mkdir: cannot create directory '/mnt/server/cs2': Permission denied
cp: target '/mnt/server/cs2/game/csgo/cfg' is not a directory
/entrypoint.sh: line 23: /mnt/server/cs2/game/csgo/cfg/autoexec.cfg: No such file or directory
/entrypoint.sh: line 55: /mnt/server/steamcmd/steamcmd.sh: No such file or directory
mkdir: cannot create directory '/mnt/server/.steam': Permission denied
mkdir: cannot create directory '/mnt/server/.steam': Permission denied
cp: cannot stat '/mnt/server/steamcmd/linux32/steamclient.so': No such file or directory
cp: cannot stat '/mnt/server/steamcmd/linux64/steamclient.so': No such file or directory
/entrypoint.sh: line 65: /mnt/server/cs2/game/cs2.sh: No such file or directory`

Can you help?

**Comment by Soren90** [comment]
How does your compose file look like?

**Comment by Hans3nn** [comment]
It works now

**Comment by Hans3nn** [comment]
I will like to get the files at the same folder as the docker-compose file

My compose: 
I remove the GSLT and the passwords
`version: "3.7"

services:
  csgo:
    image: soren90/cs2
    container_name: cs2
    environment:
      SERVER_HOSTNAME: "Counter-Strike Server"
      #SERVER_PASSWORD: "1234"
      RCON_PASSWORD: "1234"
      IP: 0.0.0.0
      PORT: 27015
      GAME_TYPE: 0
      GAME_MODE: 1
      MAP: de_mirage
      MAXPLAYERS: 12
      MAPGROUP: mg_active
      GSLT: 1234
      EXTRAARG: ""
    volumes:
      - type: bind
        source: ./csgo-data
        target: /mnt/server
    network_mode: "host"
    restart: unless-stopped
    stdin_open: true
    tty: true

  rconpanel:
    image: soren90/rcon-panel
    container_name: rcon
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./rconpanel-data
        target: /app/db

volumes:
  csgo-data:
  rconpanel-data:`
  
  
  Log:
  `/entrypoint.sh: line 55: /mnt/server/steamcmd/steamcmd.sh: No such file or directory
cp: cannot stat '/mnt/server/steamcmd/linux32/steamclient.so': No such file or directory
cp: cannot stat '/mnt/server/steamcmd/linux64/steamclient.so': No such file or directory
/entrypoint.sh: line 65: /mnt/server/cs2/game/cs2.sh: No such file or directory`

**Comment by Soren90** [comment]
> I will like to get the files at the same folder as the docker-compose file
> 
> My compose: I remove the GSLT and the passwords `version: "3.7"
> 
> services: csgo: image: soren90/cs2 container_name: cs2 environment: SERVER_HOSTNAME: "Counter-Strike Server" #SERVER_PASSWORD: "1234" RCON_PASSWORD: "1234" IP: 0.0.0.0 PORT: 27015 GAME_TYPE: 0 GAME_MODE: 1 MAP: de_mirage MAXPLAYERS: 12 MAPGROUP: mg_active GSLT: 1234 EXTRAARG: "" volumes: - type: bind source: ./csgo-data target: /mnt/server network_mode: "host" restart: unless-stopped stdin_open: true tty: true
> 
> rconpanel: image: soren90/rcon-panel container_name: rcon ports: - "3000:3000" restart: unless-stopped volumes: - type: bind source: ./rconpanel-data target: /app/db
> 
> volumes: csgo-data: rconpanel-data:`
> 
> Log: `/entrypoint.sh: line 55: /mnt/server/steamcmd/steamcmd.sh: No such file or directory cp: cannot stat '/mnt/server/steamcmd/linux32/steamclient.so': No such file or directory cp: cannot stat '/mnt/server/steamcmd/linux64/steamclient.so': No such file or directory /entrypoint.sh: line 65: /mnt/server/cs2/game/cs2.sh: No such file or directory`

Does the folder csgo-data exist? And does the user have access to write to that folder? Thats most likely the problem here.

Create the folder and do: 

`
chown 1000:1000 csgo-data
`

Might be that the userid is 1001 instead of 1000. I don't remember.
