### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by Shinku443** [Soren90/cs2-docker#14]
Just quick question - is there an environment flag for updating? Everytime theres a new update I'm having to recreate the container which redownloads the whole image

**Comment by Soren90** [comment]
Restarting the container should be enough. I looked into doing auto restarts/updates in csgo, but that was pretty buggy back then. But haven't looked into it in CS2.

I know people did a lot of workarounds around this in csgo, like having a 2nd container searching the logs for new updates and then restart the container.

I sadly don't think there is a easy way to make this happen automatically, but if you find some information about it that I've missed, I can definitely look into getting it implemented.

**Comment by Shinku443** [comment]
no problem, i appreciate it! i knew restarting fixed it as i did it for an update before just wasnt sure if there was an easy checker/updater. thank you!!
