### ISSUE TITLE
Unable to add configs.

### ISSUE THREAD

**Issue by TurtleFul** [Soren90/cs2-docker#3]
I mapped the volume to a local folder. then when I add my cfg's to cs2-data/game/csgo/cfg I just get could not find or read file prac.cfg. 
Even though its right next to your built in one's. Autoexec knife live and warmup with the same rights? 

Is this no the way to add your own configs ?

**Comment by Soren90** [comment]
Every startup the server will copy the configfiles from /mnt/cfg to the cs cfg folder:
  
```bash
# Copy competitive configs
mkdir -p ${CS2_DIR}/game/csgo/cfg
cp /mnt/cfg/* ${CS2_DIR}/game/csgo/cfg
```

This means that the easiest way to have custom configs is most likely to just bind mount the cfg folder in the repo to the /mnt/cfg folder in the container.

**Comment by m4ldotno** [comment]
@TurtleFul I have implemented @Soren90's solution in the docker-compose.yaml here:

https://github.com/EndlessUndo/cs2-docker/commit/528cbbaa30b39527eebcfb45abdabaeb87498316

Just change the ./cfg to your prefered location and restart the container

**Comment by Soren90** [comment]
I've now merged the bind mount to the repo and commented it out as we cannot guarantee that people will have the cfg folder locally, as a lot of people will only copy the docker-compose file and run that one.
