### ISSUE TITLE
game mode & type parameter are incorrect

### ISSUE THREAD

**Issue by ppaulis** [Soren90/cs2-docker#6]
https://github.com/Soren90/cs2-docker/pull/5

'gamemode' and 'gametype' must be 'game_mode' and 'game_type' instead.
Otherwise the container prints errors about invalid parameters and game style is always competitive.

**Comment by Soren90** [comment]
You are completely right. Haven't noticed this as I only host competitive servers. I have now merged your pull request.

Thanks for letting me know!
