### ISSUE TITLE
maxplayers & mapgroup parameter missing in Server start command

### ISSUE THREAD

**Issue by ppaulis** [Soren90/cs2-docker#9]
https://github.com/Soren90/cs2-docker/pull/8
Here's the PR to fix it :-)

**Comment by ppaulis** [comment]
@Soren90 You'll probably want to wait a bit before merging.. I think the maxplayers parameter is not working as expected. Working on it..

**Comment by Soren90** [comment]
@ppaulis yes. I had issues with that as well when I tested it before releasing the image, so I decided to just let it be until valve fixes it. But if you find a solution I'll definitely implement (just make sure to also set a default. 12 is good for competitive)

I'm a little busy currently, but I think I'll have time this weekend.

**Comment by ppaulis** [comment]
@Soren90 just tested a bit. The parameter seems to have a max of 16 currently. At least with bots. And it is off by 1. Meaning that if I set "-maxplayers 16", I end up with me and 14 bots on the server. The MAPGROUP parameter however works fine.

**Comment by Soren90** [comment]
I merged this to main. Thanks again for your contribution :)
